version: '3.7'
services:
    # dbhost:
    #     image: mongo:4.0.2-xenial
    #     restart: always
    #     container_name: dbhost
    #     volumes:
    #         - ~/Prog/data-warehouse:/warehouse
    #         - $HOME/data/db:/data/db
    #     ports:
    #         - "27018:27017"
    #     command: mongod --logpath=/dev/null
    nooze:
        build:
            context: ..
        # depends_on:
        #     - dbhost
        volumes:
            - $HOME/Prog/nooze/confs:/app/confs
        image: artgoldhammer/nooze310:$NZTAG
        container_name: eunews
        restart: "no"
        environment:
            NZDBCONF: /app/confs/bach-dkr-elite.conf
        entrypoint: tail -F /dev/null
        ports:
            - "9091:9090"
            - "3031:3031"
