version: '3.7'
services:
    dbhost:
        build:
            context: ~/Prog/twdb2
        image: mongo:4.0.2-xenial
        restart: always
        container_name: dbhost
        volumes:
            - ~/Prog/data-warehouse:/warehouse
            - $HOME/data/db:/data/db
        ports:
            - "27018:27017"
        command: mongod --logpath=/dev/null

    usnews:
        build:
            context: ..
        depends_on:
            - dbhost
        image: artgoldhammer/nooze:$NZTAG
        volumes:
            - $HOME/Prog/nooze/confs:/app/confs
        container_name: usnews
        restart: always
        environment:
            NZDBCONF: /app/confs/nz-dkr-test-us.conf
        ports:
            - "9090:9090"
            - "3031:3031"

    eunews:
        build:
            context: ..
        depends_on:
            - dbhost
        image: artgoldhammer/nooze:$NZTAG
        volumes:
            - $HOME/Prog/nooze/confs:/app/confs
        container_name: eunews
        restart: always
        environment:
            NZDBCONF: /app/confs/nz-dkr-test-eu.conf
        ports:
            - "9091:9090"
            - "3032:3031"
